"""accounts table

Revision ID: fca8211435fd
Revises:
Create Date: 2024-01-22 20:34:50.159133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fca8211435fd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account")),
    )
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_account_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_account_username"), ["username"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_username"))
        batch_op.drop_index(batch_op.f("ix_account_email"))

    op.drop_table("account")
    # ### end Alembic commands ###
